# Generated by Django 3.0.5 on 2020-04-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('region', models.CharField(max_length=4)),
                ('accountId', models.CharField(max_length=56)),
                ('profileIconId', models.IntegerField()),
                ('revisionDate', models.BigIntegerField()),
                ('name', models.CharField(max_length=16)),
                ('summonerId', models.CharField(max_length=63)),
                ('puuid', models.CharField(max_length=78, primary_key=True, serialize=False)),
                ('summonerLevel', models.BigIntegerField()),
            ],
        ),
    ]
