# Generated by Django 3.0.5 on 2020-04-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('region', 'accountId'), ('region', 'summonerId')},
        ),
    ]
