# Generated by Django 3.0.5 on 2020-04-21 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200412_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='flexFreshBlood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexHotStreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexInactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexLP',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexLeagueId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexLosses',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexMiniSeriesLosses',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexMiniSeriesProgress',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexMiniSeriesTarget',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexMiniSeriesWins',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexRank',
            field=models.IntegerField(blank=True, choices=[(4, 'Iv'), (3, 'Iii'), (2, 'Ii'), (1, 'I')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTier',
            field=models.CharField(blank=True, choices=[('IN', 'Iron'), ('BE', 'Bronze'), ('GD', 'Gold'), ('PN', 'Platinum'), ('DD', 'Diamond'), ('MR', 'Master'), ('GR', 'Grandmaster'), ('CR', 'Challenger')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexVeteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexWins',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloFreshBlood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloHotStreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloInactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloLP',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloLeagueId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloLosses',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloMiniSeriesLosses',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloMiniSeriesProgress',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloMiniSeriesTarget',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloMiniSeriesWins',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloRank',
            field=models.IntegerField(blank=True, choices=[(4, 'Iv'), (3, 'Iii'), (2, 'Ii'), (1, 'I')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloTier',
            field=models.CharField(blank=True, choices=[('IN', 'Iron'), ('BE', 'Bronze'), ('GD', 'Gold'), ('PN', 'Platinum'), ('DD', 'Diamond'), ('MR', 'Master'), ('GR', 'Grandmaster'), ('CR', 'Challenger')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloVeteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='soloWins',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
