# Generated by Django 3.0.5 on 2020-04-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200421_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='flexLeagueId',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='flexTier',
            field=models.CharField(blank=True, choices=[('IN', 'Iron'), ('BE', 'Bronze'), ('GD', 'Gold'), ('PN', 'Platinum'), ('DD', 'Diamond'), ('MR', 'Master'), ('GR', 'Grandmaster'), ('CR', 'Challenger')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='soloLeagueId',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='soloTier',
            field=models.CharField(blank=True, choices=[('IN', 'Iron'), ('BE', 'Bronze'), ('GD', 'Gold'), ('PN', 'Platinum'), ('DD', 'Diamond'), ('MR', 'Master'), ('GR', 'Grandmaster'), ('CR', 'Challenger')], default=None, max_length=12, null=True),
        ),
    ]
